- name: install bird
  package:
    name: bird2
- name: "Add bird config"
  template:
    dest: /etc/bird/bird.conf
    src: files/bird.conf.template
    owner: root
    mode: "0644"
  notify:
    - Restart bird
- name: "move bird into network-namespace if configured"
  when: "'netns' in bgp"
  block:
    - name: create bird.service.d directory
      file:
        path: /etc/systemd/system/bird.service.d
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: create bird.service drop-in
      copy:
        dest: /etc/systemd/system/bird.service.d/override.conf
        content: |
          [Service]
          NetworkNamespacePath=/var/run/netns/{{ bgp.netns }}
      notify:
        - Restart bird
