- name: install bird
  package:
    name: bird
- name: "Add bird config"
  template:
    dest: /etc/bird/bird.conf
    src: files/bird.conf.template
    owner: root
    mode: "0644"
  notify:
    - Restart bird
